### ISSUE TITLE
Add example from antlr4ts

### ISSUE THREAD

**Issue by batya15** [amazzalel-habib/TodoLangEditor#4]
[https://blog.nimbleways.com/create-a-custom-web-editor-using-typescript-react-antlr-and-monaco-editor-part-1-2/](Create a custom web editor using Typescript, React, ANTLR and Monaco-Editor (part 1))
> In the next part of this article, I’ll cover the language service. I’ll use ANTLR to generate TodoLang lexer and parser, implement most features of the editor using the AST provided by the parser, then we’ll see how to create a web worker to provide the language services with auto-completion.

**Comment by amazzalel-habib** [comment]
Hello @batya15 
Check the second part of the article [here ](https://medium.com/better-programming/create-a-custom-web-editor-using-typescript-react-antlr-and-monaco-editor-bcfc7554e446)

https://medium.com/better-programming/create-a-custom-web-editor-using-typescript-react-antlr-and-monaco-editor-bcfc7554e446
